version: "3.8"

services:
  batch:
    build:
      context: .
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/haru256-schedule-panel/batch/sample-batch-gpu:latest
    environment:
      - RAISE_ERROR=0
    command:
      - /bin/bash
      - -c
      - |
        python3.11 src/main.py
        tail -f /dev/null
