version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: schedule-panel
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@haru256.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    user: root

volumes:
  pgdata:
  pgadmin:
